TimeRecording: Email Class Reference
Email Class Reference
Public Member Functions
__construct ($parameters=array())
get_token ()
set_inlay ($bool=false)
add_recipient ($prefix, $email, $name="")
set_sender ($email, $name="")
set_reply ($email, $name="")
set_to ($email, $name="")
set_subject ($subject)
set_domain ($domain)
send ()
Private Member Functions
set_newlines ()
get_boundary ()
create_head ($boundary)
create_html ()
create_text ($html)
create_inline ($filename, $id, $boundary)
Private Attributes
$eol
$sol
$mailto
$domain
$borders = array()
$headers = array()
$attach = array()
$recipients = ""
$subject = ""
$useinlay = false
$template
Detailed Description
The Email:: class gives easy methods to send html mails
Patrick Kracht <patrick.kracht@googlemail.com> Thorsten Moll <thorsten.moll@googlemail.com>
Author:
Patrick Kracht <patrick.kracht@googlemail.com>
Thorsten Moll <thorsten.moll@googlemail.com>
Definition at line 13 of file class.email.php.
Constructor & Destructor Documentation
Email.__construct ($ parameters = array())
constructor creates default mail from template
Parameters:
string template name for html-email
string (optional) subject of mail
public
Author:
patrick.kracht, thorsten.moll
Reimplemented from Template.
Definition at line 37 of file class.email.php.
References Template.headers(), set_domain(), and set_newlines().
Member Function Documentation
Email.get_token ()
returns a 32bit token
Returns:
string new unique 32bit token
public
Author:
patrick.kracht, thorsten.moll
Definition at line 65 of file class.email.php.
Email.set_inlay ($ bool = false)
set usage of inlay images or use links
public
Author:
patrick.kracht, thorsten.moll
Definition at line 77 of file class.email.php.
Email.add_recipient ($ prefix, $ email, $ name = "")
add a recipient to the mail
Parameters:
string prefix: TO, CC, BCC
string email address
string (optional) name
public
Author:
patrick.kracht, thorsten.moll
Definition at line 93 of file class.email.php.
Email.set_sender ($ email, $ name = "")
set sender details (FROM) and return path
Parameters:
string email address
string (optional) name
public
Author:
patrick.kracht, thorsten.moll
Definition at line 109 of file class.email.php.
References Template.headers().
Email.set_reply ($ email, $ name = "")
set sender reply-to
Parameters:
string email address
string (optional) name
public
Author:
patrick.kracht, thorsten.moll
Definition at line 126 of file class.email.php.
References Template.headers().
Email.set_to ($ email, $ name = "")
set recipient (primary)
Parameters:
string email address
string (optional) name
public
Author:
patrick.kracht, thorsten.moll
Definition at line 142 of file class.email.php.
Email.set_subject ($ subject)
set subject of mail
Parameters:
string subject of the email
public
Author:
patrick.kracht, thorsten.moll
Definition at line 157 of file class.email.php.
References $subject.
Email.set_domain ($ domain)
set domain
Parameters:
string domain name
public
Author:
patrick.kracht, thorsten.moll
Definition at line 171 of file class.email.php.
References $domain.
Referenced by __construct().
Email.set_newlines () [private]
set special newlines for linux and windows
public
Author:
patrick.kracht, thorsten.moll
Definition at line 183 of file class.email.php.
Referenced by __construct().
Email.get_boundary () [private]
returns a boundary for embedded objects
public
Author:
patrick.kracht, thorsten.moll
Definition at line 211 of file class.email.php.
Referenced by send().
Email.create_head ($ boundary) [private]
creates multipart header with starting boundary
Parameters:
string boundary of the header
public
Author:
patrick.kracht, thorsten.moll
Definition at line 225 of file class.email.php.
References Template.headers().
Referenced by send().
Email.create_html () [private]
create parsed text from $template and return html source
public
Author:
patrick.kracht, thorsten.moll
Definition at line 243 of file class.email.php.
Referenced by send().
Email.create_text ($ html) [private]
reproduce plain text from html source, strip tags etc.
Parameters:
string html source input
Returns:
string plain-text string
public
Author:
patrick.kracht, thorsten.moll
Definition at line 259 of file class.email.php.
Referenced by send().
Email.create_inline ($ filename, $ id, $ boundary) [private]
creates an inline object in html-mail with $id and $boundary
Parameters:
string filename of the included object
string new id for this object
string boundary for separation
Returns:
string complete mail-block including file
public
Author:
patrick.kracht, thorsten.moll
Definition at line 290 of file class.email.php.
Referenced by send().
Email.send ()
create html and plain-text message, bundle with objects
Returns:
boolean status of mail function
public
Author:
patrick.kracht, thorsten.moll
Definition at line 319 of file class.email.php.
References create_head(), create_html(), create_inline(), create_text(), and get_boundary().
Member Data Documentation
Email.$eol [private]
Definition at line 15 of file class.email.php.
Email.$sol [private]
Definition at line 16 of file class.email.php.
Email.$mailto [private]
Definition at line 17 of file class.email.php.
Email.$domain [private]
Definition at line 18 of file class.email.php.
Referenced by set_domain().
Email.$borders = array() [private]
Definition at line 19 of file class.email.php.
Email.$headers = array() [private]
Definition at line 20 of file class.email.php.
Email.$attach = array() [private]
Definition at line 21 of file class.email.php.
Email.$recipients = "" [private]
Definition at line 22 of file class.email.php.
Email.$subject = "" [private]
Definition at line 23 of file class.email.php.
Referenced by set_subject().
Email.$useinlay = false [private]
Definition at line 24 of file class.email.php.
Email.$template [private]
Reimplemented from Template.
Definition at line 25 of file class.email.php.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/TimeRecording/class.email.php