TimeRecording: Template Class Reference
Template Class Reference
Public Member Functions
__construct ($parameters=array())
__destruct ()
clean_ob ()
preload ($list=false)
import ($list=false)
load ($name, $force_reload=false)
assign ($name, $search, $replace="EMPTY")
get ($name, $force_reload=false)
compress (&$buffer)
output ($name, $type="html")
get_parsed ($name)
headers ($type="html", $maxage=0)
wraplongwords (&$text, $maxlen=64)
save_newlines (&$text)
restore_newlines (&$text)
accepts_gzip ()
special_chars (&$content)
create_select ($array, $selected="")
replace_data_from_array (&$data, &$array)
align_right ($text, $maxlen=16)
menu_insert_spacer ()
menu_insert_entry ($name, $href, $access_key=false, $selected=false, $target="_self")
menu_get ()
use_database ()
Private Attributes
$template = array()
$assigned = array()
$debug_off = true
$do_compress = true
$sql_table = false
$sql_type = false
$debugout = ""
$menu_content = ""
$menu_spacer = false
$tpl_folder = "./templates/"
Detailed Description
The Template:: class implements the HTML-templates and output-engine.
Patrick Kracht <patrick.kracht@googlemail.com> Thorsten Moll <thorsten.moll@googlemail.com>
Author:
Patrick Kracht <patrick.kracht@googlemail.com>
Thorsten Moll <thorsten.moll@googlemail.com>
Definition at line 12 of file class.template.php.
Constructor & Destructor Documentation
Template.__construct ($ parameters = array())
constructor read config-file and initializes the vars
Parameters:
string config-file-location
public
Author:
patrick.kracht, thorsten.moll
Reimplemented in Email.
Definition at line 34 of file class.template.php.
Template.__destruct ()
destructor (nop)
public
Author:
patrick.kracht, thorsten.moll
Definition at line 49 of file class.template.php.
Member Function Documentation
Template.clean_ob ()
starts new clean output buffer
public
Author:
patrick.kracht, thorsten.moll
Definition at line 60 of file class.template.php.
Template.preload ($ list = false)
preload all templates by default (or selected by array/string)
Parameters:
mixed [default=false], array or string (separator ',')
public
Author:
patrick.kracht, thorsten.moll
Definition at line 79 of file class.template.php.
Template.import ($ list = false)
import all templates by default (or selected by array/string)
Parameters:
mixed [default=false], array or string (separator ',')
Returns:
mixed affected_rows by insert query (false if error)
public
Author:
patrick.kracht, thorsten.moll
Definition at line 118 of file class.template.php.
Template.load ($ name, $ force_reload = false)
loads template with $name in internal buffer-array
Parameters:
string template file name
boolean force overwriting buffer content * public
Author:
patrick.kracht, thorsten.moll
Definition at line 183 of file class.template.php.
References assign().
Referenced by get(), and output().
Template.assign ($ name, $ search, $ replace = "EMPTY")
assign a replacement in template $name
Parameters:
string template file name
mixed string (search for something) OR array key = search, value = replace
string replace with something (if $search is string)
public
Author:
patrick.kracht, thorsten.moll
Definition at line 247 of file class.template.php.
Referenced by load(), and output().
Template.get ($ name, $ force_reload = false)
returns get_parsed content of template in buffer
Parameters:
string template file name
boolean force reloading buffer content
public
Author:
patrick.kracht, thorsten.moll
Definition at line 269 of file class.template.php.
References get_parsed(), load(), and special_chars().
Template.compress (&$ buffer)
compress template (remove not needed chars)
Parameters:
&string reference to source html for compression
public
Author:
patrick.kracht, thorsten.moll
Definition at line 289 of file class.template.php.
References restore_newlines().
Referenced by output().
Template.output ($ name, $ type = "html")
finally sends complete template $name, get_parsed and compressed (if setup in config-file)
Parameters:
string template file name
string type of output (html,js,css...)
public
Author:
patrick.kracht, thorsten.moll
Definition at line 313 of file class.template.php.
References accepts_gzip(), assign(), compress(), get_parsed(), headers(), load(), menu_get(), and special_chars().
Template.get_parsed ($ name)
do replacements (if using 'assign') and returns array of parsed templates
Parameters:
string template file name
Returns:
array templates public
Author:
patrick.kracht, thorsten.moll
Definition at line 406 of file class.template.php.
Referenced by get(), and output().
Template.headers ($ type = "html", $ maxage = 0)
send headers to browser (no cookies after this point!)
Parameters:
string type of output (html,css,js,...)
public
Author:
patrick.kracht, thorsten.moll
Definition at line 424 of file class.template.php.
References accepts_gzip().
Referenced by Email.__construct(), Email.create_head(), output(), Email.set_reply(), and Email.set_sender().
Template.wraplongwords (&$ text, $ maxlen = 64)
wrap long words from $text at $maxlen (=64 default)
Parameters:
string text to wrap
string maximum length to wrap at
public
Author:
patrick.kracht, thorsten.moll
Definition at line 458 of file class.template.php.
Template.save_newlines (&$ text)
replace newlines with invisible character (to save newlines in textareas for example)
Parameters:
string text to save newlines
public
Author:
patrick.kracht, thorsten.moll
Definition at line 483 of file class.template.php.
Template.restore_newlines (&$ text)
revert saved newlines to visible
Parameters:
string text to restore newlines from
public
Author:
patrick.kracht, thorsten.moll
Definition at line 497 of file class.template.php.
Referenced by compress().
Template.accepts_gzip ()
check, if browser is accepting gzip or not an return boolean
Returns:
boolean returns TRUE or FALSE
public
Author:
patrick.kracht, thorsten.moll
Definition at line 511 of file class.template.php.
Referenced by headers(), and output().
Template.special_chars (&$ content)
replace special chars to html-wellformed equivalents
Parameters:
string text to transform
public
Author:
patrick.kracht, thorsten.moll
Definition at line 531 of file class.template.php.
Referenced by get(), and output().
Template.create_select ($ array, $ selected = "")
return a generated select-html-tag with $selected
Parameters:
mixed array or list of names separated with '|' to create a select menu from
string name of item selected (optional)
Returns:
string html select menu
public
Author:
patrick.kracht, thorsten.moll
Definition at line 560 of file class.template.php.
Template.replace_data_from_array (&$ data, &$ array)
the assign method for complete arrays
Parameters:
array index is set to $value from
array contains keys and values to set data
public
Author:
patrick.kracht, thorsten.moll
Definition at line 593 of file class.template.php.
Template.align_right ($ text, $ maxlen = 16)
return a right trimmed text with estimated $maxlen width
Parameters:
string text to align right
int width of line (=16 default)
Returns:
string aligned text (filled with spaces)
public
Author:
patrick.kracht, thorsten.moll
Definition at line 613 of file class.template.php.
Template.menu_insert_spacer ()
set spacer to next menu entry
public
Author:
patrick.kracht, thorsten.moll
Definition at line 627 of file class.template.php.
Template.menu_insert_entry ($ name, $ href, $ access_key = false, $ selected = false, $ target = "_self")
set new menu entry
Parameters:
string name of the menu entry
string href of link
char access key
boolean changes class of entry, if true
string target of link (default:_self)
public
Author:
patrick.kracht, thorsten.moll
Definition at line 645 of file class.template.php.
Template.menu_get ()
return menu string
Returns:
string menu entry
public
Author:
patrick.kracht, thorsten.moll
Definition at line 671 of file class.template.php.
Referenced by output().
Template.use_database ()
return true, if needed settings for database access are present
Returns:
boolean
public
Author:
patrick.kracht, thorsten.moll
Definition at line 687 of file class.template.php.
Member Data Documentation
Template.$template = array() [private]
Reimplemented in Email.
Definition at line 14 of file class.template.php.
Template.$assigned = array() [private]
Definition at line 15 of file class.template.php.
Template.$debug_off = true [private]
Definition at line 16 of file class.template.php.
Template.$do_compress = true [private]
Definition at line 17 of file class.template.php.
Template.$sql_table = false [private]
Definition at line 18 of file class.template.php.
Template.$sql_type = false [private]
Definition at line 19 of file class.template.php.
Template.$debugout = "" [private]
Definition at line 20 of file class.template.php.
Template.$menu_content = "" [private]
Definition at line 21 of file class.template.php.
Template.$menu_spacer = false [private]
Definition at line 22 of file class.template.php.
Template.$tpl_folder = "./templates/" [private]
Definition at line 23 of file class.template.php.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/TimeRecording/class.template.php