TimeRecording: PageLink Class Reference
PageLink Class Reference
Public Member Functions
__construct ($entrycount, $perpage=10, $maxlinks=7)
get_query_limit ()
get_page_link ($page)
__toString ()
Private Member Functions
prepare ()
generate ()
get_links_from ($start, $end)
Private Attributes
$url = "./"
$pp = 10
$ml = 7
$_data = array()
$cnt
$html
$pageid
$total_pages
$query_limit
$query_first
$query_last
Detailed Description
The PageLink:: class implements the page-link functions
Patrick Kracht <patrick.kracht@googlemail.com> Thorsten Moll <thorsten.moll@googlemail.com>
Author:
Patrick Kracht <patrick.kracht@googlemail.com>
Thorsten Moll <thorsten.moll@googlemail.com>
Definition at line 12 of file class.pagelink.php.
Constructor & Destructor Documentation
PageLink.__construct ($ entrycount, $ perpage = 10, $ maxlinks = 7)
Parameters:
string baseurl
int count of all entries (from sql)
int number of entries per page wanted
int maximum number of links displayed public
Author:
patrick.kracht, thorsten.moll
Definition at line 34 of file class.pagelink.php.
References prepare().
Member Function Documentation
PageLink.prepare () [private]
prepare some values for later usage private
Author:
patrick.kracht, thorsten.moll
Definition at line 51 of file class.pagelink.php.
Referenced by __construct().
PageLink.generate () [private]
generates whole link bar in html private
Author:
patrick.kracht, thorsten.moll
Definition at line 93 of file class.pagelink.php.
References get_links_from().
Referenced by __toString().
PageLink.get_links_from ($ start, $ end) [private]
appends pagelink or blank to html
Parameters:
int first page to display
int last page to display private
Author:
patrick.kracht, thorsten.moll
Definition at line 135 of file class.pagelink.php.
Referenced by generate().
PageLink.get_query_limit ()
returns the LIMIT x,y string for mysql queries public
Author:
patrick.kracht, thorsten.moll
Definition at line 155 of file class.pagelink.php.
PageLink.get_page_link ($ page)
returns html of one link to page number $page
Parameters:
int page number public
Author:
patrick.kracht, thorsten.moll
Definition at line 166 of file class.pagelink.php.
PageLink.__toString ()
returns complete link bar public
Author:
patrick.kracht, thorsten.moll
Definition at line 176 of file class.pagelink.php.
References generate().
Member Data Documentation
PageLink.$url = "./" [private]
Definition at line 14 of file class.pagelink.php.
PageLink.$pp = 10 [private]
Definition at line 15 of file class.pagelink.php.
PageLink.$ml = 7 [private]
Definition at line 16 of file class.pagelink.php.
PageLink.$_data = array() [private]
Definition at line 17 of file class.pagelink.php.
PageLink.$cnt [private]
Definition at line 18 of file class.pagelink.php.
PageLink.$html [private]
Definition at line 19 of file class.pagelink.php.
PageLink.$pageid [private]
Definition at line 20 of file class.pagelink.php.
PageLink.$total_pages [private]
Definition at line 21 of file class.pagelink.php.
PageLink.$query_limit [private]
Definition at line 22 of file class.pagelink.php.
PageLink.$query_first [private]
Definition at line 23 of file class.pagelink.php.
PageLink.$query_last [private]
Definition at line 24 of file class.pagelink.php.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/TimeRecording/class.pagelink.php