TimeRecording: Memory Class Reference
Memory Class Reference
Public Member Functions
__construct ()
__destruct ()
delta ()
start ()
__toString ()
Private Attributes
$umemory
Detailed Description
The Memory:: class implements memory measuring methods.
Patrick Kracht <patrick.kracht@googlemail.com> Thorsten Moll <thorsten.moll@googlemail.com>
Author:
Patrick Kracht <patrick.kracht@googlemail.com>
Thorsten Moll <thorsten.moll@googlemail.com>
Definition at line 12 of file class.memory.php.
Constructor & Destructor Documentation
Memory.__construct ()
constructor
public
Author:
patrick.kracht, thorsten.moll
Definition at line 23 of file class.memory.php.
References start().
Memory.__destruct ()
destructor
public
Author:
patrick.kracht, thorsten.moll
Definition at line 35 of file class.memory.php.
Member Function Documentation
Memory.delta ()
print delta
public
Author:
patrick.kracht, thorsten.moll
Definition at line 46 of file class.memory.php.
Memory.start ()
start measuring
public
Author:
patrick.kracht, thorsten.moll
Definition at line 58 of file class.memory.php.
Referenced by __construct().
Memory.__toString ()
to string
Returns:
string memory in use (in bytes)
public
Author:
patrick.kracht, thorsten.moll
Definition at line 72 of file class.memory.php.
References __from_bytes().
Member Data Documentation
Memory.$umemory [private]
Definition at line 14 of file class.memory.php.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/TimeRecording/class.memory.php