TimeRecording: Controller Class Reference
Controller Class Reference
Public Member Functions
__construct ()
__destruct ()
create_menu ()
create_page ()
prepare_templates ()
show_user_details ()
prepare_actions ()
Protected Member Functions
register ($classname, $parameters=array(), $alias="")
unregister ($classname, $alias="")
get_booking_sums ($range="DAY", $offset=0, $limit=1)
show_last_bookings ($limit=10)
show_user_table ($limit=10)
set_table_order ($tableid, $ordervalues, $default=0)
query2table ($query, $id, $width=array(), $details=false, $orderon=false)
Private Member Functions
reinit ()
__toString ()
Detailed Description
The Controller:: class implements the main-controller for the sytem and takes care of all registered session-objects
Patrick Kracht <patrick.kracht@googlemail.com> Thorsten Moll <thorsten.moll@googlemail.com>
Author:
Patrick Kracht <patrick.kracht@googlemail.com>
Thorsten Moll <thorsten.moll@googlemail.com>
Definition at line 13 of file class.controller.php.
Constructor & Destructor Documentation
Controller.__construct ()
constructor loads global config file and initializes default session variables, register session-objects if not set, reset needed timers
public
Author:
patrick.kracht, thorsten.moll
Reimplemented in Session.
Definition at line 24 of file class.controller.php.
References reinit().
Controller.__destruct ()
destructor
public
Author:
patrick.kracht, thorsten.moll
Reimplemented in MsSql, MySql, and Session.
Definition at line 95 of file class.controller.php.
Member Function Documentation
Controller.reinit () [private]
reinit loads global config file and initializes default session variables, register session-objects if not set, reset needed timers
private
Author:
patrick.kracht, thorsten.moll
Definition at line 38 of file class.controller.php.
References $_SETTINGS, __check_syntax(), and __session_start().
Referenced by __construct().
Controller.register ($ classname, $ parameters = array(), $ alias = "") [protected]
register new session-object, if not allready present
Parameters:
string name of object to create
array specific parameters for constructor
string (optional) alias of object
protected
Author:
patrick.kracht, thorsten.moll
Definition at line 110 of file class.controller.php.
Controller.unregister ($ classname, $ alias = "") [protected]
unregister
Parameters:
string name of object to delete
string (optional) alias of object
protected
Author:
patrick.kracht, thorsten.moll
Definition at line 132 of file class.controller.php.
Controller.__toString () [private]
to string returns null
Returns:
null
private
Author:
patrick.kracht, thorsten.moll
Definition at line 153 of file class.controller.php.
Controller.create_menu ()
creates user menu or not
public
Author:
patrick.kracht, thorsten.moll
Definition at line 165 of file class.controller.php.
Controller.create_page ()
creates user specific page
public
Author:
patrick.kracht, thorsten.moll
Definition at line 209 of file class.controller.php.
References get_booking_sums(), show_last_bookings(), show_user_details(), and show_user_table().
Controller.prepare_templates ()
prepare templates for session
public
Author:
patrick.kracht, thorsten.moll
Definition at line 321 of file class.controller.php.
Controller.get_booking_sums ($ range = "DAY", $ offset = 0, $ limit = 1) [protected]
returns sum array of bookings (week, month - current and last)
Parameters:
string type of range to sum from
int offset of first entry
int number of entries returned
Returns:
array array of all sums
protected
Author:
patrick.kracht, thorsten.moll
Definition at line 344 of file class.controller.php.
Referenced by create_page().
Controller.show_last_bookings ($ limit = 10) [protected]
returns array of all tables in database
Parameters:
int (optional) number of lines to query
Returns:
array array of all tables in database
protected
Author:
patrick.kracht, thorsten.moll
Definition at line 413 of file class.controller.php.
References query2table(), and set_table_order().
Referenced by create_page().
Controller.show_user_table ($ limit = 10) [protected]
generate html user table
protected
Author:
patrick.kracht, thorsten.moll
Definition at line 443 of file class.controller.php.
References query2table(), and set_table_order().
Referenced by create_page().
Controller.show_user_details ()
generate html details for specific userid
public
Author:
patrick.kracht, thorsten.moll
Definition at line 472 of file class.controller.php.
References query2table().
Referenced by create_page().
Controller.set_table_order ($ tableid, $ ordervalues, $ default = 0) [protected]
set sorting query
Parameters:
string tableid for sorting
array order by values, 0 = default [left to right]
int (optional) default value
protected
Author:
patrick.kracht, thorsten.moll
Definition at line 507 of file class.controller.php.
Referenced by show_last_bookings(), and show_user_table().
Controller.query2table ($ query, $ id, $ width = array(), $ details = false, $ orderon = false) [protected]
private query to html table converter
Parameters:
string sql query to get rows from
string id-tag (css stylesheet)
array (optional) width in pixel for td
boolean (optional) add col with dtails link to userid
protected
Author:
patrick.kracht, thorsten.moll
Definition at line 545 of file class.controller.php.
Referenced by show_last_bookings(), show_user_details(), and show_user_table().
Controller.prepare_actions ()
manage page actions and execute state-dependend methods
public
Author:
patrick.kracht, thorsten.moll
Definition at line 631 of file class.controller.php.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/TimeRecording/class.controller.php