TimeRecording: MsSql Class Reference
MsSql Class Reference
Public Member Functions
__construct ($parameters=array())
__destruct ()
init ()
connect ()
select_db ()
query ($qstring, $limit=0, $offset=0)
query_all ($qstring, $limit=0, $offset=0, $type=MSSQL_ASSOC)
unbuffered_query ($qstring, $LOW=0, $limit=0, $offset=0)
fetch_array ($query_id=-1, $type=MSSQL_ASSOC)#MSSQL_BOTH
Public Attributes
MSSQL_NUM
Private Attributes
$link_id
$query_id
$query_key
$mssql_error
$select_db
$hostname
$hostport
$database
$password
$username
$querytimer
Detailed Description
The MsSql:: class implements the MsSQL-Server-Connection.
Patrick Kracht <patrick.kracht@googlemail.com> Thorsten Moll <thorsten.moll@googlemail.com>
Author:
Patrick Kracht <patrick.kracht@googlemail.com>
Thorsten Moll <thorsten.moll@googlemail.com>
Definition at line 12 of file class.mssql.php.
Constructor & Destructor Documentation
MsSql.__construct ($ parameters = array())
constructor initializes the vars
Parameters:
string config-file-location
public
Author:
patrick.kracht, thorsten.moll
Implements iSql.
Definition at line 35 of file class.mssql.php.
References init().
MsSql.__destruct ()
destructor is closing connection, if present
public
Author:
patrick.kracht, thorsten.moll
Reimplemented from Controller.
Definition at line 63 of file class.mssql.php.
References iSql.close().
Member Function Documentation
MsSql.init ()
init is connecting to the mysql-server and selecting the database
public
Author:
patrick.kracht, thorsten.moll
Implements iSql.
Definition at line 75 of file class.mssql.php.
References connect(), and select_db().
Referenced by __construct(), query(), and unbuffered_query().
MsSql.connect ()
connect creates the MySQL connection and returns status
Returns:
boolean status
public
Author:
patrick.kracht, thorsten.moll
Implements iSql.
Definition at line 96 of file class.mssql.php.
Referenced by init().
MsSql.select_db ()
selects the MySQL database
Returns:
boolean status
public
Author:
patrick.kracht, thorsten.moll
Implements iSql.
Definition at line 119 of file class.mssql.php.
Referenced by init().
MsSql.query ($ qstring, $ limit = 0, $ offset = 0)
query sends querystring to server and returns queryid
Parameters:
string querystring
int start retrieving records from record
int limits number of record returned
Returns:
mixed returns MYSQL result resource on success, TRUE if no rows were returned, or FALSE on error
public
Author:
patrick.kracht, thorsten.moll
Definition at line 146 of file class.mssql.php.
References init().
Referenced by query_all().
MsSql.query_all ($ qstring, $ limit = 0, $ offset = 0, $ type = MSSQL_ASSOC)
queryall sends querystring to server and returns whole result as array
Parameters:
string querystring
int start retrieving records from record
int limits number of record returned
const the type of array that is to be fetched (default) MYSQL_ASSOC, MYSQL_NUM, MYSQL_BOTH
Returns:
array returns whole array containing all records
public
Author:
patrick.kracht, thorsten.moll
Definition at line 171 of file class.mssql.php.
References fetch_array(), iSql.free_result(), and query().
MsSql.unbuffered_query ($ qstring, $ LOW = 0, $ limit = 0, $ offset = 0)
unbuffered_query (like query, but unbuffered)
Parameters:
string querystring
int start retrieving records from record
int set low-priority commands (1) or not (0)
int limits number of record returned
Returns:
mixed returns MYSQL result resource on success, TRUE if no rows were returned, or FALSE on error
public
Author:
patrick.kracht, thorsten.moll
Definition at line 196 of file class.mssql.php.
References init().
MsSql.fetch_array ($ query_id = -1, $ type = MSSQL_ASSOC)
fetch a result row as an associative array, a numeric array, or both
Parameters:
mixed query resource
const the type of array that is to be fetched (default) MYSQL_ASSOC, MYSQL_NUM, MYSQL_BOTH
Returns:
mixed returns an array that corresponds to the fetched row, or FALSE if there are no more rows
public
Author:
patrick.kracht, thorsten.moll
Referenced by query_all().
Member Data Documentation
MsSql.$link_id [private]
Definition at line 14 of file class.mssql.php.
MsSql.$query_id [private]
Definition at line 15 of file class.mssql.php.
MsSql.$query_key [private]
Definition at line 16 of file class.mssql.php.
MsSql.$mssql_error [private]
Definition at line 17 of file class.mssql.php.
MsSql.$select_db [private]
Definition at line 18 of file class.mssql.php.
MsSql.$hostname [private]
Definition at line 19 of file class.mssql.php.
MsSql.$hostport [private]
Definition at line 20 of file class.mssql.php.
MsSql.$database [private]
Definition at line 21 of file class.mssql.php.
MsSql.$password [private]
Definition at line 22 of file class.mssql.php.
MsSql.$username [private]
Definition at line 23 of file class.mssql.php.
MsSql.$querytimer [private]
Definition at line 24 of file class.mssql.php.
MsSql.MSSQL_NUM
Definition at line 228 of file class.mssql.php.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/TimeRecording/class.mssql.php