TimeRecording: Timer Class Reference
Timer Class Reference
Public Member Functions
__construct ($parameters=array())
__destruct ()
start ()
stop ()
reset ()
get ($prec=3)
counter ()
number ()
set_units ($name)
__toString ()
Private Attributes
$counter = 0
$runtime = 0
$microtm = 0
$unitfac = 1.0
$unitstr = "s"
$namestr
Static Private Attributes
static $number = 0
Detailed Description
The Timer:: class implements time measuring methods.
Patrick Kracht <patrick.kracht@googlemail.com> Thorsten Moll <thorsten.moll@googlemail.com>
Author:
Patrick Kracht <patrick.kracht@googlemail.com>
Thorsten Moll <thorsten.moll@googlemail.com>
Definition at line 12 of file class.timer.php.
Constructor & Destructor Documentation
Timer.__construct ($ parameters = array())
constructor initializes the counter and starts it (if wanted)
Parameters:
array parameters: 0=>(string)NAME,1=>(boolean)START
public
Author:
patrick.kracht, thorsten.moll
Definition at line 31 of file class.timer.php.
References start().
Timer.__destruct ()
destructor kills the timer and decreases counter
public
Author:
patrick.kracht, thorsten.moll
Definition at line 49 of file class.timer.php.
Member Function Documentation
Timer.start ()
start current timer
public
Author:
patrick.kracht, thorsten.moll
Definition at line 61 of file class.timer.php.
Referenced by __construct().
Timer.stop ()
stop timer and increase total runtime and ticks counter
public
Author:
patrick.kracht, thorsten.moll
Definition at line 73 of file class.timer.php.
References counter().
Referenced by __toString(), and get().
Timer.reset ()
resets current counter to zero
public
Author:
patrick.kracht, thorsten.moll
Definition at line 87 of file class.timer.php.
References counter().
Timer.get ($ prec = 3)
get
Parameters:
int (optional) precision [default:3]
Returns:
double amount of time since first start
public
Author:
patrick.kracht, thorsten.moll
Definition at line 107 of file class.timer.php.
References stop().
Timer.counter ()
get number of timeslices from timer
Returns:
int number of timeslices
public
Author:
patrick.kracht, thorsten.moll
Definition at line 127 of file class.timer.php.
Referenced by __toString(), reset(), and stop().
Timer.number ()
get number of counters registered
Returns:
int number of counters
public
Author:
patrick.kracht, thorsten.moll
Definition at line 141 of file class.timer.php.
Timer.set_units ($ name)
set units system
Parameters:
string unit to use for output [us|ms|s]
public
Author:
patrick.kracht, thorsten.moll
Definition at line 155 of file class.timer.php.
Timer.__toString ()
to string
Returns:
string [COUNTER] trigger(s) from '[NAME]' lasted [DURATION] [UNIT];
public
Author:
patrick.kracht, thorsten.moll
Definition at line 185 of file class.timer.php.
References counter(), and stop().
Member Data Documentation
Timer.$number = 0 [static, private]
Definition at line 14 of file class.timer.php.
Timer.$counter = 0 [private]
Definition at line 15 of file class.timer.php.
Timer.$runtime = 0 [private]
Definition at line 16 of file class.timer.php.
Timer.$microtm = 0 [private]
Definition at line 17 of file class.timer.php.
Timer.$unitfac = 1.0 [private]
Definition at line 18 of file class.timer.php.
Timer.$unitstr = "s" [private]
Definition at line 19 of file class.timer.php.
Timer.$namestr [private]
Definition at line 20 of file class.timer.php.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/TimeRecording/class.timer.php