TimeRecording: Session Class Reference
Session Class Reference
Public Member Functions
__construct ()
__destruct ()
logout ($error_message="")
login ()
passwd ()
book ()
update ()
delete ()
create ()
generate_password ($length=8)
is_admin ()
is_user ()
return_to ($url)
extend ()
valid ()
started ()
randomize ()
valid_email ($email, $check_db=false)
is_secure_password ($password, $min_len=8)
Private Member Functions
get_mx_records ($host, $type="MX")
Detailed Description
The Session:: class manages login functions and security using sessions
Patrick Kracht <patrick.kracht@googlemail.com> Thorsten Moll <thorsten.moll@googlemail.com>
Author:
Patrick Kracht <patrick.kracht@googlemail.com>
Thorsten Moll <thorsten.moll@googlemail.com>
Definition at line 12 of file class.session.php.
Constructor & Destructor Documentation
Session.__construct ()
constructor
public
Author:
patrick.kracht, thorsten.moll
Reimplemented from Controller.
Definition at line 22 of file class.session.php.
Session.__destruct ()
destructor (nop)
public
Author:
patrick.kracht, thorsten.moll
Reimplemented from Controller.
Definition at line 33 of file class.session.php.
Member Function Documentation
Session.logout ($ error_message = "")
logout destroys session and starts a new one in guest mode and reload page
public
Author:
patrick.kracht, thorsten.moll
Definition at line 45 of file class.session.php.
References return_to().
Referenced by extend(), and login().
Session.login ()
perform login with POST values $_POST["LoginUsername"] and $_POST["LoginPassword"]
Returns:
boolean success of login action
public
Author:
patrick.kracht, thorsten.moll
Definition at line 66 of file class.session.php.
References extend(), and logout().
Session.passwd ()
reset a password for a given username (email) and returns new generated password
Parameters:
string username (email)
Returns:
string new generated password
public
Author:
patrick.kracht, thorsten.moll
Definition at line 118 of file class.session.php.
References generate_password().
Session.book ()
booking method with symbol for userid
Parameters:
int symbol id to set
int userid to set (optional)
Returns:
int affected rows
public
Author:
patrick.kracht, thorsten.moll
Definition at line 189 of file class.session.php.
References generate_password(), and is_user().
Session.update ()
update method
public
Author:
patrick.kracht, thorsten.moll
Definition at line 282 of file class.session.php.
Session.delete ()
delete method
public
Author:
patrick.kracht, thorsten.moll
Definition at line 294 of file class.session.php.
Session.create ()
create method
public
Author:
patrick.kracht, thorsten.moll
Definition at line 306 of file class.session.php.
Session.generate_password ($ length = 8)
generates a new random password with $length
Parameters:
int length of the generated password
Returns:
string new generated password
public
Author:
patrick.kracht, thorsten.moll
Definition at line 322 of file class.session.php.
References randomize().
Referenced by book(), and passwd().
Session.is_admin ()
checks current user for admin rights
Returns:
boolean TRUE = is admin
public
Author:
patrick.kracht, thorsten.moll
Definition at line 349 of file class.session.php.
Session.is_user ()
checks current user for user rights
Returns:
boolean TRUE = is user
public
Author:
patrick.kracht, thorsten.moll
Definition at line 364 of file class.session.php.
Referenced by book().
Session.return_to ($ url)
redirect to any $url using header-location
public
Author:
patrick.kracht, thorsten.moll
Definition at line 377 of file class.session.php.
Referenced by logout().
Session.extend ()
extend current session, if valid anymore, or logout after timeout const SESSION_TIMEOUT seconds
public
Author:
patrick.kracht, thorsten.moll
Definition at line 391 of file class.session.php.
References logout(), started(), and valid().
Referenced by login().
Session.valid ()
checks, if current session is started and valid (logout after timeout const SESSION_TIMEOUT seconds)
Returns:
boolean returns true, if session is valid
public
Author:
patrick.kracht, thorsten.moll
Definition at line 421 of file class.session.php.
Referenced by extend().
Session.started ()
checks, if current session is started
Returns:
boolean returns true, if session is started
public
Author:
patrick.kracht, thorsten.moll
Definition at line 443 of file class.session.php.
Referenced by extend().
Session.randomize ()
restarts the mt_srand with some better randomized init values
public
Author:
patrick.kracht, thorsten.moll
Definition at line 456 of file class.session.php.
Referenced by generate_password().
Session.valid_email ($ email, $ check_db = false)
check, is an $email is valid (RegEx, DB and MX-check)
Parameters:
string email address for checking
boolean check email in database too?
Returns:
boolean if the $email is a valid one
public
Author:
patrick.kracht, thorsten.moll
Definition at line 474 of file class.session.php.
Session.get_mx_records ($ host, $ type = "MX") [private]
get mx-records from host (optional: $type)
Parameters:
string host to contact and query MX
string (optional) type of record
Returns:
array complete list of records using nslookup
public
Author:
patrick.kracht, thorsten.moll
Definition at line 565 of file class.session.php.
Session.is_secure_password ($ password, $ min_len = 8)
proof choosen password for a better security
Parameters:
string password to check
int minimum length of password
Returns:
boolean if the $password is a good one
public
Author:
patrick.kracht, thorsten.moll
Definition at line 595 of file class.session.php.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/TimeRecording/class.session.php