TimeRecording: MySql Class Reference
MySql Class Reference
Public Member Functions
__construct ($parameters=array())
__destruct ()
init ()
connect ()
select_db ()
query ($qstring, $limit=0, $offset=0)
query_all ($qstring, $limit=0, $offset=0, $type=MYSQL_ASSOC)
unbuffered_query ($qstring, $LOW=0, $limit=0, $offset=0)
fetch_array ($query_id=-1, $type=MYSQL_ASSOC)
fetch_row ($query_id=-1)
query_first ($qstring, $limit=0, $offset=0, $type=MYSQL_ASSOC)
num_rows ($query_id=-1)
affected_rows ($link_id=-1)
insert_id ($link_id=-1)
free_result (&$result)
close ($link_id=-1)
show_tables ()
html_table ($tablename, $where="")
Private Attributes
$link_id
$query_id
$query_key
$mysql_error
$mysql_errno
$select_db
$hostname
$database
$password
$username
Detailed Description
The MySql:: class implements the MySQL-Server-Connection.
Patrick Kracht <patrick.kracht@googlemail.com> Thorsten Moll <thorsten.moll@googlemail.com>
Author:
Patrick Kracht <patrick.kracht@googlemail.com>
Thorsten Moll <thorsten.moll@googlemail.com>
Definition at line 12 of file class.mysql.php.
Constructor & Destructor Documentation
MySql.__construct ($ parameters = array())
constructor initializes the vars
Parameters:
string config-file-location
public
Author:
patrick.kracht, thorsten.moll
Implements iSql.
Definition at line 34 of file class.mysql.php.
References init().
MySql.__destruct ()
destructor is closing connection, if present
public
Author:
patrick.kracht, thorsten.moll
Reimplemented from Controller.
Definition at line 63 of file class.mysql.php.
References close().
Member Function Documentation
MySql.init ()
init is connecting to the mysql-server and selecting the database
public
Author:
patrick.kracht, thorsten.moll
Implements iSql.
Definition at line 75 of file class.mysql.php.
References connect(), and select_db().
Referenced by __construct(), query(), and unbuffered_query().
MySql.connect ()
connect creates the MySQL connection and returns status
Returns:
boolean status
public
Author:
patrick.kracht, thorsten.moll
Implements iSql.
Definition at line 96 of file class.mysql.php.
Referenced by init().
MySql.select_db ()
selects the MySQL database
Returns:
boolean status
public
Author:
patrick.kracht, thorsten.moll
Implements iSql.
Definition at line 119 of file class.mysql.php.
Referenced by init().
MySql.query ($ qstring, $ limit = 0, $ offset = 0)
query sends querystring to server and returns queryid
Parameters:
string querystring
int start retrieving records from record
int limits number of record returned
Returns:
mixed returns MYSQL result resource on success, TRUE if no rows were returned, or FALSE on error
public
Author:
patrick.kracht, thorsten.moll
Definition at line 146 of file class.mysql.php.
References init().
Referenced by html_table(), query_all(), query_first(), and show_tables().
MySql.query_all ($ qstring, $ limit = 0, $ offset = 0, $ type = MYSQL_ASSOC)
queryall sends querystring to server and returns whole result as array
Parameters:
string querystring
int start retrieving records from record
int limits number of record returned
const the type of array that is to be fetched (default) MYSQL_ASSOC, MYSQL_NUM, MYSQL_BOTH
Returns:
array returns whole array containing all records
public
Author:
patrick.kracht, thorsten.moll
Definition at line 171 of file class.mysql.php.
References fetch_array(), free_result(), and query().
MySql.unbuffered_query ($ qstring, $ LOW = 0, $ limit = 0, $ offset = 0)
unbuffered_query (like query, but unbuffered)
Parameters:
string querystring
int start retrieving records from record
int set low-priority commands (1) or not (0)
int limits number of record returned
Returns:
mixed returns MYSQL result resource on success, TRUE if no rows were returned, or FALSE on error
public
Author:
patrick.kracht, thorsten.moll
Definition at line 196 of file class.mysql.php.
References init().
MySql.fetch_array ($ query_id = -1, $ type = MYSQL_ASSOC)
fetch a result row as an associative array, a numeric array, or both
Parameters:
mixed query resource
const the type of array that is to be fetched (default) MYSQL_ASSOC, MYSQL_NUM, MYSQL_BOTH
Returns:
mixed returns an array that corresponds to the fetched row, or FALSE if there are no more rows
public
Author:
patrick.kracht, thorsten.moll
Definition at line 228 of file class.mysql.php.
References $query_id.
Referenced by html_table(), query_all(), and query_first().
MySql.fetch_row ($ query_id = -1)
get row as enumerated array
Parameters:
mixed query resource
Returns:
mixed returns an array that corresponds to the fetched row, or FALSE if there are no more rows
public
Author:
patrick.kracht, thorsten.moll
Implements iSql.
Definition at line 249 of file class.mysql.php.
References $query_id.
Referenced by show_tables().
MySql.query_first ($ qstring, $ limit = 0, $ offset = 0, $ type = MYSQL_ASSOC)
query_first sends querystring to server and returns array
Parameters:
string querystring
int start retrieving records from record
int limits number of record returned
const the type of array that is to be fetched (default) MYSQL_ASSOC, MYSQL_NUM, MYSQL_BOTH
Returns:
array returns array containing first records
public
Author:
patrick.kracht, thorsten.moll
Definition at line 273 of file class.mysql.php.
References fetch_array(), free_result(), and query().
MySql.num_rows ($ query_id = -1)
gets the number of rows in result
Parameters:
mixed query resource
Returns:
int number of rows
public
Author:
patrick.kracht, thorsten.moll
Implements iSql.
Definition at line 292 of file class.mysql.php.
References $query_id.
MySql.affected_rows ($ link_id = -1)
gets the number of rows in result
Parameters:
mixed link resource
Returns:
int number of rows
public
Author:
patrick.kracht, thorsten.moll
Implements iSql.
Definition at line 312 of file class.mysql.php.
References $link_id.
MySql.insert_id ($ link_id = -1)
gets id of last insert query
Parameters:
mixed link resource
Returns:
int id of last insert
public
Author:
patrick.kracht, thorsten.moll
Implements iSql.
Definition at line 332 of file class.mysql.php.
References $link_id.
MySql.free_result (&$ result)
frees result of previous query
Parameters:
mixed MYSQL result resource to free
public
Author:
patrick.kracht, thorsten.moll
Implements iSql.
Definition at line 350 of file class.mysql.php.
Referenced by query_all(), and query_first().
MySql.close ($ link_id = -1)
closes mysql-connection
Parameters:
mixed link resource
public
Author:
patrick.kracht, thorsten.moll
Implements iSql.
Definition at line 365 of file class.mysql.php.
References $link_id.
Referenced by __destruct().
MySql.show_tables ()
returns array of all tables in database
public
Author:
patrick.kracht, thorsten.moll
Implements iSql.
Definition at line 378 of file class.mysql.php.
References fetch_row(), and query().
MySql.html_table ($ tablename, $ where = "")
generate html string sql table
Returns:
array array of all tables in database
public
Author:
patrick.kracht, thorsten.moll
Definition at line 396 of file class.mysql.php.
References fetch_array(), and query().
Member Data Documentation
MySql.$link_id [private]
Definition at line 14 of file class.mysql.php.
Referenced by affected_rows(), close(), and insert_id().
MySql.$query_id [private]
Definition at line 15 of file class.mysql.php.
Referenced by fetch_array(), fetch_row(), and num_rows().
MySql.$query_key [private]
Definition at line 16 of file class.mysql.php.
MySql.$mysql_error [private]
Definition at line 17 of file class.mysql.php.
MySql.$mysql_errno [private]
Definition at line 18 of file class.mysql.php.
MySql.$select_db [private]
Definition at line 19 of file class.mysql.php.
MySql.$hostname [private]
Definition at line 20 of file class.mysql.php.
MySql.$database [private]
Definition at line 21 of file class.mysql.php.
MySql.$password [private]
Definition at line 22 of file class.mysql.php.
MySql.$username [private]
Definition at line 23 of file class.mysql.php.
The documentation for this class was generated from the following file:
C:/xampp/htdocs/TimeRecording/class.mysql.php