TimeRecording: C:/xampp/htdocs/TimeRecording/functions.php File Reference
C:/xampp/htdocs/TimeRecording/functions.php File Reference
Functions
__session_start ($name="sid")
__autoload ($class_name)
__check_syntax ($filename)
__from_bytes ($val, $prec=0, $cnt=0)
Function Documentation
__autoload ($ class_name)
autoload class files
Parameters:
string class name
public
Author:
patrick.kracht, thorsten.moll
Definition at line 82 of file functions.php.
__check_syntax ($ filename)
check syntax of php file (config file)
Parameters:
string filename to check
Returns:
boolean true: valid syntax, false: errors
public
Author:
patrick.kracht, thorsten.moll
Definition at line 107 of file functions.php.
Referenced by Controller.reinit().
__from_bytes ($ val, $ prec = 0, $ cnt = 0)
convert php.ini values bytes to KB, MB, GB...
Parameters:
int value in bytes
int precision
int shifting amount
Returns:
string formatted bytes
public
Author:
patrick.kracht, thorsten.moll
Definition at line 130 of file functions.php.
Referenced by Memory.__toString().
__session_start ($ name = "sid")
GLOBAL FUNCTIONS - TIMERECORDING
Patrick Kracht <patrick.kracht@googlemail.com> Thorsten Moll <thorsten.moll@googlemail.com>
Author:
Patrick Kracht <patrick.kracht@googlemail.com>
Thorsten Moll <thorsten.moll@googlemail.com> start a valid session with name
Parameters:
string session name
public
Author:
patrick.kracht, thorsten.moll
Definition at line 22 of file functions.php.
Referenced by Controller.reinit().